chore: update OpenWrt build workflow by commenting out jobs and adding permissions

diff --git a/.github/workflows/openwrt-build.yml b/.github/workflows/openwrt-build.yml
--- a/.github/workflows/openwrt-build.yml
+++ b/.github/workflows/openwrt-build.yml
@@ -13,122 +13,128 @@ on:
   #     - main
   #     - develop
 
+permissions:
+  contents: write
+  packages: write
+  id-token: write
+  pull-requests: write
+
 # Define the jobs that will be executed as part of this workflow.
 jobs:
-  checkout-openwrt:
-    name: Clean and Checkout OpenWrt Repository
-    runs-on: self-hosted
-    steps:
-      - name: Clean OpenWrt Repository
-        run: |
-          rm -rf openwrt
-          rm -rf mtk-openwrt-feeds
-      - name: Checkout Workflow Repository
-        uses: actions/checkout@v4
+  # checkout-openwrt:
+  #   name: Clean and Checkout OpenWrt Repository
+  #   runs-on: self-hosted
+  #   steps:
+  #     - name: Clean OpenWrt Repository
+  #       run: |
+  #         rm -rf openwrt
+  #         rm -rf mtk-openwrt-feeds
+  #     - name: Checkout Workflow Repository
+  #       uses: actions/checkout@v4
 
         
-  pull-repositories:
-    name: Pull Repositories
-    runs-on: self-hosted
-    needs: checkout-openwrt
-    steps:
-      - name: Clean OpenWrt Repository
-        run: |
-          rm -rf openwrt
-          rm -rf mtk-openwrt-feeds
-      - name: Pull OpenWrt Repository
-        run: |
-          python3 script.py
-      - name: Switch to OpenWrt 24.10
-        run: |
-          cd openwrt
-          git switch openwrt-24.10
-      - name: Fetch Repositories
-        run: |
-          cd openwrt
-          git pull
-          cd ..
-          cd mtk-openwrt-feeds
-          git pull
+  # pull-repositories:
+  #   name: Pull Repositories
+  #   runs-on: self-hosted
+  #   needs: checkout-openwrt
+  #   steps:
+  #     - name: Clean OpenWrt Repository
+  #       run: |
+  #         rm -rf openwrt
+  #         rm -rf mtk-openwrt-feeds
+  #     - name: Pull OpenWrt Repository
+  #       run: |
+  #         python3 script.py
+  #     - name: Switch to OpenWrt 24.10
+  #       run: |
+  #         cd openwrt
+  #         git switch openwrt-24.10
+  #     - name: Fetch Repositories
+  #       run: |
+  #         cd openwrt
+  #         git pull
+  #         cd ..
+  #         cd mtk-openwrt-feeds
+  #         git pull
 
 
-  configure-openwrt-feeds:
-    name: Configure MTK Feeds
-    # Specify the runner environment. 'ubuntu-latest' is a GitHub-hosted runner.
-    # For very resource-intensive builds, consider using a 'self-hosted' runner.
-    # needs: pull-repositories
-    runs-on: self-hosted
-    needs: pull-repositories
-    steps:
-      - name: Configure Feed Revisions
-        working-directory: openwrt
-        run: |
-          # Set shell options for robustness: exit on error, treat unset variables as error, print commands.
-          set -euo pipefail
-          echo "packages de909258525bdb3e227c8e6fc1b61329e9a11f62" > ../mtk-openwrt-feeds/autobuild/unified/feed_revision
-          echo "luci 8d367398d626436e67478da447ce4a4ffe7992e2" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
-          echo "routing d53907107d48331ef38978f7a259bc8eac3765a0" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
-          echo "telephony 44d6355a7b2d69dd25d73913811b421fc504b836" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
-          echo "video 1668ab74cf47cdec753895e70007083ba9c69fe4" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
+  # configure-openwrt-feeds:
+  #   name: Configure MTK Feeds
+  #   # Specify the runner environment. 'ubuntu-latest' is a GitHub-hosted runner.
+  #   # For very resource-intensive builds, consider using a 'self-hosted' runner.
+  #   # needs: pull-repositories
+  #   runs-on: self-hosted
+  #   needs: pull-repositories
+  #   steps:
+  #     - name: Configure Feed Revisions
+  #       working-directory: openwrt
+  #       run: |
+  #         # Set shell options for robustness: exit on error, treat unset variables as error, print commands.
+  #         set -euo pipefail
+  #         echo "packages de909258525bdb3e227c8e6fc1b61329e9a11f62" > ../mtk-openwrt-feeds/autobuild/unified/feed_revision
+  #         echo "luci 8d367398d626436e67478da447ce4a4ffe7992e2" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
+  #         echo "routing d53907107d48331ef38978f7a259bc8eac3765a0" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
+  #         echo "telephony 44d6355a7b2d69dd25d73913811b421fc504b836" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
+  #         echo "video 1668ab74cf47cdec753895e70007083ba9c69fe4" >> ../mtk-openwrt-feeds/autobuild/unified/feed_revision
 
-  start-docker-container:
-    name: Start Docker Container
-    runs-on: self-hosted
-    needs: configure-openwrt-feeds
-    steps:
-      - name: Start Docker Container
-        run: |
-          docker stop openwrt-imagebuilder || true
-          docker rm openwrt-imagebuilder || true
-          docker run --name openwrt-imagebuilder --rm --user $(id -u):$(id -g) --ulimit 'nofile=1024:262144' --volume "$(pwd):/workdir" --workdir '/workdir' -d openwrt/imagebuilder:mediatek-filogic  /bin/bash -c 'sleep infinity'
+  # start-docker-container:
+  #   name: Start Docker Container
+  #   runs-on: self-hosted
+  #   needs: configure-openwrt-feeds
+  #   steps:
+  #     - name: Start Docker Container
+  #       run: |
+  #         docker stop openwrt-imagebuilder || true
+  #         docker rm openwrt-imagebuilder || true
+  #         docker run --name openwrt-imagebuilder --rm --user $(id -u):$(id -g) --ulimit 'nofile=1024:262144' --volume "$(pwd):/workdir" --workdir '/workdir' -d openwrt/imagebuilder:mediatek-filogic  /bin/bash -c 'sleep infinity'
 
-  build-mtk-openwrt-feeds:
-    name: Build MTK Feeds
-    runs-on: self-hosted
-    needs: start-docker-container
-    steps:
-      - name: Run mtk-openwrt-feeds Autobuild Script
-        run: |
-          set -euo pipefail
-          docker exec openwrt-imagebuilder /bin/bash -c 'cd openwrt && ../mtk-openwrt-feeds/autobuild/unified/autobuild.sh filogic-mac80211-mt7988_rfb-mt7996 log_file=make'
+  # build-mtk-openwrt-feeds:
+  #   name: Build MTK Feeds
+  #   runs-on: self-hosted
+  #   needs: start-docker-container
+  #   steps:
+  #     - name: Run mtk-openwrt-feeds Autobuild Script
+  #       run: |
+  #         set -euo pipefail
+  #         docker exec openwrt-imagebuilder /bin/bash -c 'cd openwrt && ../mtk-openwrt-feeds/autobuild/unified/autobuild.sh filogic-mac80211-mt7988_rfb-mt7996 log_file=make'
 
-  defconfig:
-    name: Configure OpenWrt
-    runs-on: self-hosted
-    needs: build-mtk-openwrt-feeds
-    steps:
-      - name: Configure OpenWrt
-        run: |
-          echo 'CONFIG_PINCTRL_MT7987=y' >> openwrt/target/linux/mediatek/filogic/config-6.6
-          echo 'CONFIG_COMMON_CLK_MT7987=y' >> openwrt/target/linux/mediatek/filogic/config-6.6
-      - name: Defconfig
-        working-directory: openwrt
-        run: |
-          docker exec openwrt-imagebuilder /bin/bash -c 'cd openwrt && make defconfig'
+  # defconfig:
+  #   name: Configure OpenWrt
+  #   runs-on: self-hosted
+  #   needs: build-mtk-openwrt-feeds
+  #   steps:
+  #     - name: Configure OpenWrt
+  #       run: |
+  #         echo 'CONFIG_PINCTRL_MT7987=y' >> openwrt/target/linux/mediatek/filogic/config-6.6
+  #         echo 'CONFIG_COMMON_CLK_MT7987=y' >> openwrt/target/linux/mediatek/filogic/config-6.6
+  #     - name: Defconfig
+  #       working-directory: openwrt
+  #       run: |
+  #         docker exec openwrt-imagebuilder /bin/bash -c 'cd openwrt && make defconfig'
 
-  build-openwrt:
-    name: Build OpenWrt
-    # Specify the runner environment. 'ubuntu-latest' is a GitHub-hosted runner.
-    # For very resource-intensive builds, consider using a 'self-hosted' runner.
-    # needs: pull-repositories
-    runs-on: self-hosted
-    needs: defconfig
-      # Step 6: Run the main OpenWrt autobuild script.
-      # allowing the relative path to 'mtk-openwrt-feeds' to work correctly.
-    steps:
-      # Step 7: Run the main OpenWrt autobuild script.
-      # The 'working-directory' ensures the script runs from the 'openwrt' directory,
-      # allowing the relative path to 'mtk-openwrt-feeds' to work correctly.
-      - name: Run OpenWrt Build
-        working-directory: openwrt
-        run: |
-          set -euo pipefail
-          docker exec openwrt-imagebuilder /bin/bash -c 'cd openwrt && make -j$(($(nproc)+1)) V=s'
+  # build-openwrt:
+  #   name: Build OpenWrt
+  #   # Specify the runner environment. 'ubuntu-latest' is a GitHub-hosted runner.
+  #   # For very resource-intensive builds, consider using a 'self-hosted' runner.
+  #   # needs: pull-repositories
+  #   runs-on: self-hosted
+  #   needs: defconfig
+  #     # Step 6: Run the main OpenWrt autobuild script.
+  #     # allowing the relative path to 'mtk-openwrt-feeds' to work correctly.
+  #   steps:
+  #     # Step 7: Run the main OpenWrt autobuild script.
+  #     # The 'working-directory' ensures the script runs from the 'openwrt' directory,
+  #     # allowing the relative path to 'mtk-openwrt-feeds' to work correctly.
+  #     - name: Run OpenWrt Build
+  #       working-directory: openwrt
+  #       run: |
+  #         set -euo pipefail
+  #         docker exec openwrt-imagebuilder /bin/bash -c 'cd openwrt && make -j$(($(nproc)+1)) V=s'
 
   upload-artifacts:
     name: Upload Artifacts
     runs-on: self-hosted
-    needs: build-openwrt
+    # needs: build-openwrt
     steps:
       # - name: Upload Artifacts
       #   uses: actions/upload-artifact@v4
